export const priceOracleAbi = [
  {
    inputs: [
      { internalType: "address", name: "_wethAddress", type: "address" },
      { internalType: "address", name: "_wethUsdPairAddress", type: "address" },
      { internalType: "address", name: "_uniswapV2FactoryAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "PairDoesNotContainBase", type: "error" },
  { inputs: [], name: "PairDoesNotExist", type: "error" },
  {
    inputs: [],
    name: "UNISWAP_V2_FACTORY_ADDRESS",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "WETH_ADDRESS", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "WETH_DECIMALS", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "WETH_USD_PAIR_ADDRESS", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenLiquidityUsd",
    outputs: [{ internalType: "uint256", name: "totalLiquidityUsd18", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenLiquidityWeth",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenMarketCapUsd",
    outputs: [{ internalType: "uint256", name: "marketCapUsd18", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenMarketCapWeth",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenUsdPrice",
    outputs: [{ internalType: "uint256", name: "price18", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenWethPairAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tokenAddress", type: "address" }],
    name: "getTokenWethPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getWethUsdPrice", outputs: [{ internalType: "uint256", name: "price18", type: "uint256" }], stateMutability: "view", type: "function" },
] as const;
